## Data Pre Processing

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
one=preprocessing.OneHotEncoder()
le=preprocessing.LabelEncoder()
minmax=preprocessing.MinMaxScaler()
std=preprocessing.StandardScaler()

### 'NA' Values

In [4]:
data={'one':pd.Series([1,2,5],index=['a','b','e']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
table=pd.DataFrame(data)
table

,one,two
a,1.0,1.0
b,2.0,2.0
c,NaN,3.0
d,NaN,4.0
e,5.0,NaN


In [5]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer
imputer.fit(table)
data_trans=imputer.transform(table)
data_trans=pd.DataFrame(data_trans,columns=['one','two'])
data_trans

,one,two
0,1.000000,1.0
1,2.000000,2.0
2,2.666667,3.0
3,2.666667,4.0
4,5.000000,2.5


In [7]:
imputer=SimpleImputer(missing_values=np.nan,strategy='median')
imputer
imputer.fit(table)
data_trans=imputer.transform(table)
data_trans=pd.DataFrame(data_trans,columns=['one','two'])
data_trans

,one,two
0,1.0,1.0
1,2.0,2.0
2,2.0,3.0
3,2.0,4.0
4,5.0,2.5


In [42]:
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer
imputer.fit(table)
data_trans=imputer.transform(table)
data_trans=pd.DataFrame(data_trans,columns=['one','two'])
data_trans

,one,two
0,1.0,1.0
1,2.0,2.0
2,1.0,3.0
3,1.0,4.0
4,5.0,1.0


In [28]:
x=table.fillna(20)
x

,one,two
a,1.0,1.0
b,2.0,2.0
c,20.0,3.0
d,20.0,4.0
e,5.0,20.0


## Handling the Categorical Data (get_dummies)

In [2]:
import pandas as pd
data={'customer_id':pd.Series([1,2,3,4,5]),
      'loan_type':pd.Series(['Home loan','Personal loan','Education loan','Car loan','Credit loan']),
     'Income':pd.Series(['15k','20k','30k','40k','50k'])}
data=pd.DataFrame(data)
data

,customer_id,loan_type,Income
0,1,Home loan,15k
1,2,Personal loan,20k
2,3,Education loan,30k
3,4,Car loan,40k
4,5,Credit loan,50k


In [3]:
loan_info=pd.get_dummies(data)
print(loan_info)

   customer_id  loan_type_Car loan  loan_type_Credit loan  \
0            1               False                  False   
1            2               False                  False   
2            3               False                  False   
3            4                True                  False   
4            5               False                   True   

   loan_type_Education loan  loan_type_Home loan  loan_type_Personal loan  \
0                     False                 True                    False   
1                     False                False                     True   
2                      True                False                    False   
3                     False                False                    False   
4                     False                False                    False   

   Income_15k  Income_20k  Income_30k  Income_40k  Income_50k  
0        True       False       False       False       False  
1       False        True       False     

In [73]:
loan_info=pd.get_dummies(data,dtype=int)
print(loan_info)

   customer_id  loan_type_Car loan  loan_type_Credit loan  \
0            1                   0                      0   
1            2                   0                      0   
2            3                   0                      0   
3            4                   1                      0   
4            5                   0                      1   

   loan_type_Education loan  loan_type_Home loan  loan_type_Personal loan  \
0                         0                    1                        0   
1                         0                    0                        1   
2                         1                    0                        0   
3                         0                    0                        0   
4                         0                    0                        0   

   Income_15k  Income_20k  Income_30k  Income_40k  Income_50k  
0           1           0           0           0           0  
1           0           1           0     

In [75]:
loan_info=pd.get_dummies(data,prefix_sep='_',drop_first=True,dtype=int)
print(loan_info)

   customer_id  loan_type_Credit loan  loan_type_Education loan  \
0            1                      0                         0   
1            2                      0                         0   
2            3                      0                         1   
3            4                      0                         0   
4            5                      1                         0   

   loan_type_Home loan  loan_type_Personal loan  Income_20k  Income_30k  \
0                    1                        0           0           0   
1                    0                        1           1           0   
2                    0                        0           0           1   
3                    0                        0           0           0   
4                    0                        0           0           0   

   Income_40k  Income_50k  
0           0           0  
1           0           0  
2           0           0  
3           1           0  
4     

## Handling the Categorical Data (OneHotEncoder())

In [82]:
from sklearn.preprocessing import OneHotEncoder

In [83]:
data={'customer_id':pd.Series([1,2,3,4,5]),
      'loan_type':pd.Series(['Home loan','Personal loan','Education loan','Car loan','Credit loan']),
     'Income':pd.Series(['15k','20k','30k','40k','50k'])}
data=pd.DataFrame(data)
data

,customer_id,loan_type,Income
0,1,Home loan,15k
1,2,Personal loan,20k
2,3,Education loan,30k
3,4,Car loan,40k
4,5,Credit loan,50k


In [84]:
One=OneHotEncoder()
x=One.fit_transform(data).toarray()
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Handling the Categorical Data (LabelEncoder())

In [86]:
from sklearn.preprocessing import LabelEncoder

In [87]:
data={'customer_id':pd.Series([1,2,3,4,5]),
      'loan_type':pd.Series(['Home loan','Personal loan','Education loan','Car loan','Credit loan']),
     'Income':pd.Series(['15k','20k','30k','40k','50k'])}
data=pd.DataFrame(data)
data

,customer_id,loan_type,Income
0,1,Home loan,15k
1,2,Personal loan,20k
2,3,Education loan,30k
3,4,Car loan,40k
4,5,Credit loan,50k


In [94]:
label=LabelEncoder()
y=data.apply(label.fit_transform)
y

,customer_id,loan_type,Income
0,0,3,0
1,1,4,1
2,2,2,2
3,3,0,3
4,4,1,4


## Scalling the Data: StandardScalar()

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [8]:
data=np.array([[-100.3],[27.5],[0],[-200.0],[1000]])
print('before sclalling \n',data)
standard_scalar=preprocessing.StandardScaler()
Scaled=standard_scalar.fit_transform(data)
print('After sclalling \n',Scaled)


before sclalling 
 [[-100.3]
 [  27.5]
 [   0. ]
 [-200. ]
 [1000. ]]
After sclalling 
 [[-0.56524004]
 [-0.27128026]
 [-0.33453451]
 [-0.79456547]
 [ 1.96562028]]


In [2]:
data=np.array([[-100.3],[27.5],[0],[-200.0],[1000]])
data

array([[-100.3],
       [  27.5],
       [   0. ],
       [-200. ],
       [1000. ]])

In [8]:
stdscaler=preprocessing.StandardScaler()
scaledata=stdscaler.fit_transform(data)
scaledata

array([[-0.56524004],
       [-0.27128026],
       [-0.33453451],
       [-0.79456547],
       [ 1.96562028]])

## Scalling the Data: MinMAxScaler()

In [9]:
data=np.array([[-100.3],[27.5],[0],[-200.0],[1000]])
print('before sclalling \n',data)
Minmax_Scalerr=preprocessing.MinMaxScaler(feature_range=(1,2))
Scaled=standard_scalar.fit_transform(data)
print('After sclalling \n',Scaled)


before sclalling 
 [[-100.3]
 [  27.5]
 [   0. ]
 [-200. ]
 [1000. ]]
After sclalling 
 [[1.08308333]
 [1.18958333]
 [1.16666667]
 [1.        ]
 [2.        ]]


In [17]:
data=np.array([[-100.3],[27.5],[0],[-200.0],[1000]])
data
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax

MinMaxScaler()

In [18]:
scaledata2=minmax.fit_transform(data)
scaledata2

array([[0.08308333],
       [0.18958333],
       [0.16666667],
       [0.        ],
       [1.        ]])

## Scalling the Data: RobustScaler()

In [10]:
data=np.array([[-100.3],[27.5],[0],[-200.0],[1000]])
print('before sclalling \n',data)
Robust_scalar=preprocessing.RobustScaler()
Scaled=standard_scalar.fit_transform(data)
print('After sclalling \n',Scaled)

before sclalling 
 [[-100.3]
 [  27.5]
 [   0. ]
 [-200. ]
 [1000. ]]
After sclalling 
 [[-0.78482003]
 [ 0.21517997]
 [ 0.        ]
 [-1.56494523]
 [ 7.82472613]]


In [19]:
data=np.array([[-100.3],[27.5],[0],[-200.0],[1000]])
data
robust=preprocessing.RobustScaler()
robust

RobustScaler()

In [20]:
scaleddata3=robust.fit_transform(data)
scaleddata3

array([[-0.78482003],
       [ 0.21517997],
       [ 0.        ],
       [-1.56494523],
       [ 7.82472613]])

In [ ]:
## Scalling the Data: Normalization

In [13]:
data=np.array([[5.1,3.5,1.4,0.2],[4.9,3.0,1.4,0.2],
               [4.7,3.2,1.3,0.2],[4.6,3.1,1.4,0.2],
               [5.0,3.6,1.4,0.2]])
print('before sclalling \n',data)
normalize=preprocessing.normalize(data)
print('After sclalling \n',normalize)

before sclalling 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.4 0.2]
 [5.  3.6 1.4 0.2]]
After sclalling 
 [[0.80377277 0.55160877 0.22064351 0.0315205 ]
 [0.82813287 0.50702013 0.23660939 0.03380134]
 [0.80533308 0.54831188 0.2227517  0.03426949]
 [0.80356241 0.54153119 0.24456247 0.0349375 ]
 [0.790965   0.5694948  0.2214702  0.0316386 ]]


In [21]:
data=np.array([[5.1,3.5,1.4,0.2],[4.9,3.0,1.4,0.2],
               [4.7,3.2,1.3,0.2],[4.6,3.1,1.4,0.2],
               [5.0,3.6,1.4,0.2]])
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [23]:
norm=preprocessing.normalize(data)
norm

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80356241, 0.54153119, 0.24456247, 0.0349375 ],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ]])

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
titanic=pd.read_csv('titanic.csv')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [5]:
titanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


## USe Preprocessing technique for the above data

## Data Preprocessing 

In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [3]:
hotel = pd.read_csv('hotel_bookings.csv')
hotel

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07


In [4]:
hotel.head(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03


In [5]:
hotel.sample(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
66321,City Hotel,1,34,2017,April,16,17,1,1,1,...,No Deposit,9.0,NaN,0,Transient,129.00,0,0,Canceled,2017-03-22
103148,City Hotel,0,5,2016,December,50,10,2,1,2,...,No Deposit,9.0,NaN,0,Transient,125.33,0,1,Check-Out,2016-12-13
33072,Resort Hotel,0,15,2017,February,6,11,2,1,2,...,No Deposit,240.0,NaN,0,Transient,65.00,1,2,Check-Out,2017-02-14
542,Resort Hotel,0,19,2015,July,30,19,1,0,2,...,No Deposit,240.0,NaN,0,Transient,120.60,1,1,Check-Out,2015-07-20
58357,City Hotel,1,40,2016,October,42,11,0,3,2,...,No Deposit,85.0,NaN,0,Transient,96.30,0,0,Canceled,2016-09-26


In [6]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [7]:
hotel.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [8]:
hotel_book=hotel.drop(['company','agent'],axis=1)

In [9]:
hotel_book.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,391.000000,5400.000000,8.000000,5.000000


In [10]:
hotel_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 30 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [11]:
hotel_book.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car

In [12]:
hotel_book=hotel_book.fillna(hotel_book['country'].value_counts().index[0])

In [13]:
#hotel_book['country'].value_counts().index[0]

In [14]:
hotel_book['country'].isnull().sum()

0

In [ ]:
hotel.duplicated().sum()

In [ ]:
hotel.drop_duplicates()

In [ ]:
hotel.isnull().sum()

In [ ]:
hotel.nunique()

In [15]:
hotel_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 30 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119390 non-null  object 
 11  babies                          119390 non-null  int64  
 12  meal            

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
label_encode=LabelEncoder()

In [18]:
hotel_book['country'].sample(5)

3959      FRA
92555     PRT
57853     BEL
85147     NLD
109747    FIN
Name: country, dtype: object

In [19]:
#hotel_book['country']=hotel_book['country'].astype(str)

In [20]:
hotel_book['country']=label_encode.fit_transform(hotel_book['country'])

In [21]:
hotel_book['country'].sample(5)
#hotel_book

58786    135
40360    135
65       169
38543     81
43826    135
Name: country, dtype: int32

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [29]:
hotel_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 30 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119390 non-null  object 
 11  babies                          119390 non-null  int64  
 12  meal            

In [ ]:
# delete columns whose data type int32 and int64
hotel_book=hotel_book.select_dtypes(include=['int32','int64','float64']).columns

In [30]:
hotel_cat=hotel_book.drop(columns=hotel_book.select_dtypes(include=['int32','int64','float64']).columns)

In [42]:
hotel_cat

,hotel,arrival_date_month,children,meal,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,July,0.0,BB,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
1,Resort Hotel,July,0.0,BB,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
2,Resort Hotel,July,0.0,BB,Direct,Direct,A,C,No Deposit,Transient,Check-Out,2015-07-02
3,Resort Hotel,July,0.0,BB,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out,2015-07-02
4,Resort Hotel,July,0.0,BB,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,August,0.0,BB,Offline TA/TO,TA/TO,A,A,No Deposit,Transient,Check-Out,2017-09-06
119386,City Hotel,August,0.0,BB,Online TA,TA/TO,E,E,No Deposit,Transient,Check-Out,2017-09-07
119387,City Hotel,August,0.0,BB,Online TA,TA/TO,D,D,No Deposit,Transient,Check-Out,2017-09-07
119388,City Hotel,August,0.0,BB,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2017-09-07


In [31]:
hotel_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   hotel                    119390 non-null  object
 1   arrival_date_month       119390 non-null  object
 2   children                 119390 non-null  object
 3   meal                     119390 non-null  object
 4   market_segment           119390 non-null  object
 5   distribution_channel     119390 non-null  object
 6   reserved_room_type       119390 non-null  object
 7   assigned_room_type       119390 non-null  object
 8   deposit_type             119390 non-null  object
 9   customer_type            119390 non-null  object
 10  reservation_status       119390 non-null  object
 11  reservation_status_date  119390 non-null  object
dtypes: object(12)
memory usage: 10.9+ MB


In [46]:
hotel_cat=hotel_cat.copy()

In [ ]:
hotel1 = pd.DataFrame(
    one.fit_transform(hotel[['arrival_date_month']]).toarray(),  
    columns=one.get_feature_names_out(['arrival_date_month'])  
)

In [3]:
data={'customer_id':pd.Series([1,2,3,4,5]),
      'loan_type':pd.Series(['Home loan','Personal loan','Education loan','Car loan','Credit loan']),
     'Income':pd.Series(['15k','20k','30k','40k','50k'])}
data=pd.DataFrame(data)
data

,customer_id,loan_type,Income
0,1,Home loan,15k
1,2,Personal loan,20k
2,3,Education loan,30k
3,4,Car loan,40k
4,5,Credit loan,50k


In [5]:
from sklearn.preprocessing import OneHotEncoder

# Extracting only the categorical column
loan_type_data = data[['loan_type']]
print(loan_type_data)

        loan_type
0       Home loan
1   Personal loan
2  Education loan
3        Car loan
4     Credit loan


In [7]:
 #Create an instance of the encoder
encoder = OneHotEncoder(sparse=False)

# Fit and transform the column
encoded_array = encoder.fit_transform(loan_type_data)
print(encoded_array)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


C:\Users\Vaidehi\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [9]:
encoded_df = pd.DataFrame(encoded_array) #, columns=encoder.get_feature_names_out(['loan_type'])
print(encoded_df)

     0    1    2    3    4
0  0.0  0.0  0.0  1.0  0.0
1  0.0  0.0  0.0  0.0  1.0
2  0.0  0.0  1.0  0.0  0.0
3  1.0  0.0  0.0  0.0  0.0
4  0.0  1.0  0.0  0.0  0.0
